version: '3.5'

services:

  ros-master:
    image: ros:noetic-ros-core
    container_name: roscore
    network_mode: host
    command: stdbuf -o L roscore
    restart: always

  ricoh_theta_ros:
    container_name: ricoh_theta_ros
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    privileged: true
    network_mode: host
    environment:
      - ROS_MASTER_URI=http://localhost:11311
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
    depends_on:
      - ros-master
    command: rosrun ricoh_theta_ros start.sh
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /dev:/dev  # Added for device access